# Generated by Django 5.2.14 on 2026-06-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_homeworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainHosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('domain', 'Domain'), ('hosting', 'Hosting')], max_length=10, verbose_name='service type')),
                ('service_name', models.CharField(help_text='e.g. example.com or hosting plan name', max_length=255, verbose_name='service name')),
                ('provider', models.CharField(blank=True, default='', max_length=200, verbose_name='provider / registrar')),
                ('registration_date', models.DateField(verbose_name='registration date')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('renewal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='renewal amount')),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='GST %')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=10, verbose_name='status')),
                ('nameserver', models.CharField(blank=True, default='', max_length=255, verbose_name='nameserver')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='expiry reminder sent')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_hosting_services', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'domain / hosting',
                'verbose_name_plural': 'domains / hosting',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='DomainHostingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50, verbose_name='invoice number')),
                ('invoice_date', models.DateField(verbose_name='invoice date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='paid date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hosting.domainhosting', verbose_name='service')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
