# Generated by Django 5.2.14 on 2026-07-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_location_options_remove_location_client_and_more'),
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualMaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='AMC title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('expiry_date', models.DateField(verbose_name='expiry date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='pending', max_length=10, verbose_name='payment status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amcs', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'annual maintenance contract',
                'verbose_name_plural': 'annual maintenance contracts',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
