/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './accounts/templates/**/*.html',
        './accounts/**/*.py',
        './dpmservice/**/*.py',
        './assets/templates/**/*.html',
        './clients/templates/**/*.html',
        './dashboard/templates/**/*.html',
        './hosting/templates/**/*.html',
        './masters/templates/**/*.html',
        './network/templates/**/*.html',
        './tickets/templates/**/*.html',
        './comments/templates/**/*.html',
        './notifications/templates/**/*.html',
        './authorization/templates/**/*.html',
    ],
    theme: {
        extend: {},
    },
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            {
                light: {
                    "color-scheme": "light",
                    "primary": "#545454",
                    "primary-content": "#FFFFFF",
                    "secondary": "#545454",
                    "secondary-content": "#FFFFFF",
                    "accent": "#545454",
                    "accent-content": "#FFFFFF",
                    "neutral": "#CCCCCC",
                    "neutral-content": "#545454",
                    "base-100": "#FFFFFF",
                    "base-200": "#F5F5F5",
                    "base-300": "#E5E5E5",
                    "base-content": "#545454",
                    "info": "#3B82F6",
                    "info-content": "#FFFFFF",
                    "success": "#10B981",
                    "success-content": "#FFFFFF",
                    "warning": "#F9E32F",
                    "warning-content": "#545454",
                    "error": "#EF4444",
                    "error-content": "#FFFFFF",
                },
            },
            {
                dark: {
                    "color-scheme": "dark",
                    "primary": "#F9E32F",
                    "primary-content": "#545454",
                    "secondary": "#CCCCCC",
                    "secondary-content": "#1A1A1A",
                    "accent": "#F9E32F",
                    "accent-content": "#545454",
                    "neutral": "#545454",
                    "neutral-content": "#CCCCCC",
                    "base-100": "#1A1A1A",
                    "base-200": "#2A2A2A",
                    "base-300": "#3A3A3A",
                    "base-content": "#CCCCCC",
                    "info": "#60A5FA",
                    "info-content": "#1A1A1A",
                    "success": "#34D399",
                    "success-content": "#1A1A1A",
                    "warning": "#F9E32F",
                    "warning-content": "#545454",
                    "error": "#F87171",
                    "error-content": "#1A1A1A",
                },
            },
        ],
        darkTheme: 'dark',
        base: true,
        styled: true,
        utils: true,
        logs: false,
    },
};
