# Generated by Django 5.2.14 on 2026-06-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('cidr', models.CharField(help_text='e.g. 192.168.1.0/24', max_length=18, unique=True, verbose_name='CIDR notation')),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, verbose_name='gateway')),
                ('vlan_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='VLAN ID')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnets', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'subnet',
                'verbose_name_plural': 'subnets',
                'ordering': ['cidr'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='device name')),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('other', 'Other')], default='other', max_length=20, verbose_name='device type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='management IP')),
                ('mac_address', models.CharField(blank=True, default='', max_length=17, verbose_name='MAC address')),
                ('brand', models.CharField(blank=True, default='', max_length=100, verbose_name='brand')),
                ('model_name', models.CharField(blank=True, default='', max_length=150, verbose_name='model')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='serial number')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_devices', to='clients.client', verbose_name='client')),
                ('subnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='network.subnet', verbose_name='subnet')),
            ],
            options={
                'verbose_name': 'network device',
                'verbose_name_plural': 'network devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable')], default='available', max_length=20, verbose_name='status')),
                ('hostname', models.CharField(blank=True, default='', max_length=200, verbose_name='hostname')),
                ('mac_address', models.CharField(blank=True, default='', help_text='Format: AA:BB:CC:DD:EE:FF', max_length=17, verbose_name='MAC address')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='clients.client', verbose_name='client')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='network.subnet', verbose_name='subnet')),
            ],
            options={
                'verbose_name': 'IP address',
                'verbose_name_plural': 'IP addresses',
                'ordering': ['subnet', 'ip_address'],
                'unique_together': {('subnet', 'ip_address')},
            },
        ),
    ]
