# Generated by Django 5.2.14 on 2026-06-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ip_address',
            field=models.CharField(max_length=45, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='subnet',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='subnet'),
        ),
    ]
