# Generated by Django 5.2.14 on 2026-06-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_homeworker'),
        ('network', '0002_networkdevice_password_networkdevice_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='homeworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='clients.homeworker', verbose_name='homeworker'),
        ),
    ]
