# Generated by Django 5.2.14 on 2026-07-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_networkdevice_homeworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='homeworker',
        ),
    ]
