# Generated by Django 5.2.14 on 2026-06-03 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Unique identifier for the asset.', max_length=50, unique=True, verbose_name='asset tag')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='serial number')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model_name', models.CharField(max_length=150, verbose_name='model name')),
                ('specifications', models.TextField(blank=True, default='', help_text='Technical specifications (RAM, CPU, Storage, etc.).', verbose_name='specifications')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='purchase date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='purchase price')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='warranty expiry')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('retired', 'Retired'), ('lost', 'Lost')], default='available', max_length=20, verbose_name='status')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='masters.assettype', verbose_name='asset type')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='clients.client', verbose_name='client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='clients.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='assigned date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='return date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset', verbose_name='asset')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='clients.client', verbose_name='client')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='clients.employee', verbose_name='assigned to employee')),
            ],
            options={
                'verbose_name': 'asset assignment',
                'verbose_name_plural': 'asset assignments',
                'ordering': ['-assigned_date'],
            },
        ),
    ]
