# Generated by Django 5.2.14 on 2026-06-08 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('clients', '0002_homeworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='employee',
        ),
        migrations.AddField(
            model_name='asset',
            name='homeworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='clients.homeworker', verbose_name='homeworker'),
        ),
        migrations.AddField(
            model_name='assetassignment',
            name='homeworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to='clients.homeworker', verbose_name='assigned to homeworker'),
        ),
    ]
