# Generated by Django 5.2.14 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_replace_employee_with_homeworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Unique identifier for the asset.', max_length=50, unique=True, verbose_name='asset tag'),
        ),
    ]
