# Generated by Django 5.2.14 on 2026-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='asset',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='username'),
        ),
    ]
