# Generated by Django 5.2.14 on 2026-07-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_update_asset_fields'),
        ('clients', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='clients.location', verbose_name='location'),
        ),
    ]
