# Generated by Django 5.2.14 on 2026-07-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='device_location',
            field=models.CharField(blank=True, default='', help_text='Physical location of the device (e.g. Building A, Floor 3, Desk 12).', max_length=255, verbose_name='device location'),
        ),
    ]
