# Generated by Django 5.2.14 on 2026-07-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_device_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='brand_model',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='brand/model'),
        ),
    ]
