# Generated by Django 5.2.14 on 2026-07-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_make_brand_model_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
    ]
