# Generated by Django 5.2.14 on 2026-07-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_asset_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='homeworker',
        ),
        migrations.RemoveField(
            model_name='assetassignment',
            name='homeworker',
        ),
    ]
