# Generated by Django 5.2.14 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='comments/attachments/', verbose_name='attachment'),
        ),
    ]
