# Generated by Django 5.2.14 on 2026-06-03 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='company name')),
                ('contact_person', models.CharField(max_length=150, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='alternate phone')),
                ('address', models.TextField(verbose_name='address')),
                ('pincode', models.CharField(max_length=10, verbose_name='pincode')),
                ('gst_number', models.CharField(blank=True, default='', max_length=20, verbose_name='GST number')),
                ('pan_number', models.CharField(blank=True, default='', max_length=20, verbose_name='PAN number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='masters.city', verbose_name='city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='masters.state', verbose_name='state')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='employee ID')),
                ('designation', models.CharField(max_length=100, verbose_name='designation')),
                ('department', models.CharField(choices=[('operations', 'Operations'), ('technical', 'Technical'), ('administration', 'Administration'), ('logistics', 'Logistics'), ('support', 'Support')], default='operations', max_length=20, verbose_name='department')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='alternate phone')),
                ('address', models.TextField(blank=True, default='', verbose_name='address')),
                ('pincode', models.CharField(blank=True, default='', max_length=10, verbose_name='pincode')),
                ('joining_date', models.DateField(verbose_name='joining date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='masters.city', verbose_name='city')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='masters.state', verbose_name='state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['employee_id'],
            },
        ),
    ]
