# Generated by Django 5.2.14 on 2026-06-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('pincode', models.CharField(max_length=10, verbose_name='pincode')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homeworkers', to='masters.city', verbose_name='city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworkers', to='clients.client', verbose_name='client')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homeworkers', to='masters.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'homeworker',
                'verbose_name_plural': 'homeworkers',
                'ordering': ['name'],
            },
        ),
    ]
