# Generated by Django 5.2.14 on 2026-06-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_homeworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='employees/aadhar/', verbose_name='Aadhar card'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='employee photo'),
        ),
    ]
