# Generated by Django 5.2.14 on 2026-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_employee_aadhar_card_employee_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='employee ID'),
        ),
    ]
