# Generated by Django 5.2.14 on 2026-06-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_allow_blank_employee_id'),
        ('clients', '0005_create_users_for_existing_clients'),
    ]

    operations = [
    ]
