# Generated by Django 5.2.14 on 2026-06-30 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_merge_20260630_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
    ]
