# Generated by Django 5.2.14 on 2026-07-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_employee_joining_date'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='location name')),
                ('address', models.TextField(verbose_name='address')),
                ('pincode', models.CharField(blank=True, default='', max_length=10, verbose_name='pincode')),
                ('contact_person', models.CharField(blank=True, default='', max_length=150, verbose_name='contact person')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='masters.city', verbose_name='city')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clients.client', verbose_name='client')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='masters.state', verbose_name='state')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['client', 'name'],
            },
        ),
    ]
