# Generated by Django 5.2.14 on 2026-07-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='client',
        ),
        migrations.RemoveField(
            model_name='location',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='location',
            name='contact_phone',
        ),
    ]
