# Generated by Django 5.2.14 on 2026-07-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_asset_homeworker_and_more'),
        ('clients', '0010_branch_client_branch_employee_branches'),
        ('network', '0004_remove_networkdevice_homeworker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homeworker',
        ),
    ]
