# Generated by Django 5.2.14 on 2026-07-08 09:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('tagline', models.CharField(blank=True, default='', max_length=255, verbose_name='tagline')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='state')),
                ('pincode', models.CharField(blank=True, default='', max_length=10, verbose_name='pincode')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='country')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, default='', verbose_name='website')),
                ('gst_number', models.CharField(blank=True, default='', max_length=20, verbose_name='GST number')),
                ('pan_number', models.CharField(blank=True, default='', max_length=20, verbose_name='PAN number')),
                ('cin_number', models.CharField(blank=True, default='', help_text='Company Identification Number', max_length=30, verbose_name='CIN number')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo displayed on light backgrounds', null=True, upload_to=accounts.models.company_logo_path, verbose_name='logo (light theme)')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo displayed on dark backgrounds', null=True, upload_to=accounts.models.company_logo_path, verbose_name='logo (dark theme)')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=30, verbose_name='bank account number')),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=20, verbose_name='bank IFSC code')),
                ('bank_branch', models.CharField(blank=True, default='', max_length=200, verbose_name='bank branch')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'company info',
                'verbose_name_plural': 'company info',
            },
        ),
    ]
