# Generated by Django 5.2.14 on 2026-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('security', models.CharField(choices=[('tls', 'TLS (STARTTLS)'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='tls', max_length=4, verbose_name='encryption')),
                ('username', models.CharField(blank=True, default='', max_length=200, verbose_name='username')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='password')),
                ('from_email', models.EmailField(blank=True, default='', help_text='Used as the sender address for all outgoing emails', max_length=254, verbose_name='default from email')),
                ('from_name', models.CharField(blank=True, default='', help_text='Display name shown in the from field', max_length=200, verbose_name='from name')),
                ('is_active', models.BooleanField(default=False, verbose_name='enable email sending')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'mail settings',
                'verbose_name_plural': 'mail settings',
            },
        ),
    ]
