# Generated by Django 5.2.14 on 2026-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_mailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', help_text='Secret key for TOTP two-factor authentication', max_length=32, verbose_name='TOTP secret key'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled', verbose_name='two-factor enabled'),
        ),
    ]
