# Generated by Django 5.2.14 on 2026-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_totp_secret_user_two_factor_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=200, verbose_name='MSG91 auth key')),
                ('sender_id', models.CharField(help_text='6-character alphanumeric sender ID', max_length=6, verbose_name='sender ID')),
                ('route', models.CharField(choices=[('1', 'Promotional'), ('4', 'Transactional')], default='4', max_length=2, verbose_name='route')),
                ('country', models.PositiveIntegerField(default=91, verbose_name='country code')),
                ('is_active', models.BooleanField(default=False, verbose_name='enable SMS sending')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'SMS settings',
                'verbose_name_plural': 'SMS settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(max_length=200, verbose_name='MSG91 auth key')),
                ('template_id', models.CharField(blank=True, default='', help_text='Default WhatsApp template ID for notifications', max_length=200, verbose_name='template ID')),
                ('whatsapp_number', models.CharField(blank=True, default='', help_text='Sender WhatsApp number with country code', max_length=20, verbose_name='WhatsApp business number')),
                ('is_active', models.BooleanField(default=False, verbose_name='enable WhatsApp sending')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'WhatsApp settings',
                'verbose_name_plural': 'WhatsApp settings',
            },
        ),
    ]
