# Generated by Django 5.2.14 on 2026-07-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_smssettings_whatsappsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssettings',
            name='auth_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='MSG91 auth key'),
        ),
        migrations.AlterField(
            model_name='whatsappsettings',
            name='auth_key',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='MSG91 auth key'),
        ),
    ]
