# Generated by Django 5.2.14 on 2026-06-22 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('dashboard', 'Dashboard'), ('clients', 'Clients'), ('employees', 'Employees'), ('homeworkers', 'Homeworkers'), ('assets', 'Assets'), ('devices', 'Devices'), ('tickets', 'Tickets'), ('domain_hosting', 'Domain & Hosting'), ('notifications', 'Notifications'), ('settings', 'Settings'), ('authorization', 'Authorization & Roles')], max_length=50, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('assign', 'Assign'), ('revoke', 'Revoke'), ('clone', 'Clone')], max_length=20, verbose_name='action')),
                ('model_name', models.CharField(max_length=100, verbose_name='model')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='object ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=300, verbose_name='object repr')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url_name', models.CharField(max_length=200, verbose_name='URL name')),
                ('icon', models.CharField(blank=True, default='', max_length=200, verbose_name='icon class')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authorization.menuitem', verbose_name='parent')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='authorization.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='authorization.group', verbose_name='group')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON dict of permission: true/false', verbose_name='permissions')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='authorization.module', verbose_name='module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'module permission',
                'verbose_name_plural': 'module permissions',
                'unique_together': {('role', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('networkdevice', 'Network Device'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('state', 'State'), ('city', 'City'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON dict of permission: true/false', verbose_name='permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_permissions', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'model permission',
                'verbose_name_plural': 'model permissions',
                'unique_together': {('role', 'model')},
            },
        ),
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authorization.menuitem', verbose_name='menu item')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'menu permission',
                'verbose_name_plural': 'menu permissions',
                'unique_together': {('role', 'menu_item')},
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('networkdevice', 'Network Device'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('state', 'State'), ('city', 'City'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model')),
                ('field_name', models.CharField(max_length=200, verbose_name='field name')),
                ('permission', models.CharField(choices=[('hidden', 'Hidden'), ('readonly', 'Read Only'), ('editable', 'Editable')], default='editable', max_length=10, verbose_name='permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'field permission',
                'verbose_name_plural': 'field permissions',
                'unique_together': {('role', 'model', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_assignments', to='authorization.group', verbose_name='group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='authorization.role', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user role assignment',
                'verbose_name_plural': 'user role assignments',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
