# Generated by Django 5.2.14 on 2026-06-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='model',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('state', 'State'), ('city', 'City'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='model',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('state', 'State'), ('city', 'City'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model'),
        ),
    ]
