# Generated by Django 5.2.14 on 2026-07-11 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_fieldpermission_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_created', models.BooleanField(default=True, verbose_name='ticket created')),
                ('ticket_completed', models.BooleanField(default=True, verbose_name='ticket completed')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='authorization.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'notification setting',
                'verbose_name_plural': 'notification settings',
                'unique_together': {('role',)},
            },
        ),
    ]
