# Generated by Django 5.2.14 on 2026-08-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_notification_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpermission',
            name='model',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('networkdevice', 'Network Device'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('hostinginvoice', 'Hosting Invoice'), ('amc', 'AMC'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('transporttype', 'Transport Type'), ('state', 'State'), ('city', 'City'), ('location', 'Location'), ('branch', 'Branch'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='modelpermission',
            name='model',
            field=models.CharField(choices=[('client', 'Client'), ('employee', 'Employee'), ('homeworker', 'Homeworker'), ('asset', 'Asset'), ('assetassignment', 'Asset Assignment'), ('subnet', 'Subnet'), ('ipaddress', 'IP Address'), ('networkdevice', 'Network Device'), ('serviceticket', 'Service Ticket'), ('ticketcomment', 'Ticket Comment'), ('tickethistory', 'Ticket History'), ('domainhosting', 'Domain & Hosting'), ('hostinginvoice', 'Hosting Invoice'), ('amc', 'AMC'), ('servicetype', 'Service Type'), ('assettype', 'Asset Type'), ('transporttype', 'Transport Type'), ('state', 'State'), ('city', 'City'), ('location', 'Location'), ('branch', 'Branch'), ('user', 'User'), ('group', 'Group'), ('role', 'Role')], max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('clients', 'Clients'), ('employees', 'Employees'), ('homeworkers', 'Homeworkers'), ('assets', 'Assets'), ('devices', 'Devices'), ('tickets', 'Tickets'), ('domain_hosting', 'Domain & Hosting'), ('notifications', 'Notifications'), ('settings', 'Settings'), ('authorization', 'Authorization & Roles'), ('masters', 'Masters'), ('ai', 'AI'), ('system', 'System')], max_length=50, unique=True, verbose_name='code'),
        ),
    ]
