# Generated by Django 5.2.14 on 2026-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AICacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_hash', models.CharField(db_index=True, help_text='SHA256 hash of system + user prompt.', max_length=64, unique=True, verbose_name='prompt hash')),
                ('response', models.JSONField(verbose_name='response')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('tokens_input', models.PositiveIntegerField(default=0, verbose_name='input tokens')),
                ('tokens_output', models.PositiveIntegerField(default=0, verbose_name='output tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='expires at')),
            ],
            options={
                'verbose_name': 'AI cache entry',
                'verbose_name_plural': 'AI cache entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='e.g. search, classify, suggest, chat', max_length=50, verbose_name='feature')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('tokens_input', models.PositiveIntegerField(verbose_name='input tokens')),
                ('tokens_output', models.PositiveIntegerField(verbose_name='output tokens')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='cost estimate (USD)')),
                ('response_time_ms', models.PositiveIntegerField(verbose_name='response time (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='success')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'AI usage log',
                'verbose_name_plural': 'AI usage logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='ai_aiusagel_feature_6bdbf9_idx')],
            },
        ),
    ]
