# Generated by Django 5.2.14 on 2026-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('mistral', 'Mistral AI'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom Provider')], default='openai', max_length=20, verbose_name='provider')),
                ('api_key', models.CharField(blank=True, default='', help_text='API key for the selected provider. Leave blank to use environment variable.', max_length=500, verbose_name='API key')),
                ('model_name', models.CharField(default='gpt-4o-mini', help_text='e.g. gpt-4o-mini, gemini-2.0-flash, deepseek-chat', max_length=100, verbose_name='model name')),
                ('base_url', models.URLField(blank=True, default='', help_text='Custom API base URL. Leave blank for provider default.', verbose_name='base URL')),
                ('max_tokens', models.PositiveIntegerField(default=500, verbose_name='max tokens')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.3, max_digits=3, verbose_name='temperature')),
                ('cache_ttl', models.PositiveIntegerField(default=86400, help_text='How long to cache AI responses (seconds).', verbose_name='cache TTL (seconds)')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=1.0, help_text='Maximum daily spend limit in USD.', max_digits=10, verbose_name='daily budget (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
