# Generated by Django 5.2.14 on 2026-06-03 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('clients', '0001_initial'),
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='ticket number')),
                ('ticket_type', models.CharField(choices=[('pickup', 'Pickup'), ('drop', 'Drop'), ('maintenance', 'Maintenance')], max_length=20, verbose_name='ticket type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20, verbose_name='status')),
                ('subject', models.CharField(max_length=200, verbose_name='subject')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='scheduled date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='completed date')),
                ('pickup_address', models.TextField(blank=True, default='', verbose_name='pickup address')),
                ('drop_address', models.TextField(blank=True, default='', verbose_name='drop address')),
                ('contact_person', models.CharField(blank=True, default='', max_length=150, verbose_name='contact person')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='contact phone')),
                ('notes', models.TextField(blank=True, default='', verbose_name='internal notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='assets.asset', verbose_name='asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='clients.employee', verbose_name='assigned to')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='clients.client', verbose_name='client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='masters.servicetype', verbose_name='service type')),
            ],
            options={
                'verbose_name': 'service ticket',
                'verbose_name_plural': 'service tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.serviceticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket comment',
                'verbose_name_plural': 'ticket comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100, verbose_name='field')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='old value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='new value')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='changed at')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_history', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.serviceticket', verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'ticket history',
                'verbose_name_plural': 'ticket histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
