# Generated by Django 5.2.14 on 2026-06-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='tracking_url',
            field=models.URLField(blank=True, default='', help_text='Public tracking URL for the service status.', max_length=500, verbose_name='tracking URL'),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='transport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='masters.transporttype', verbose_name='transport type'),
        ),
    ]
