# Generated by Django 5.2.14 on 2026-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_transport_type_and_tracking_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='drop_address',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='address'),
        ),
    ]
