# Generated by Django 5.2.14 on 2026-07-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_location'),
        ('tickets', '0003_remove_ticket_type_add_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='clients.location', verbose_name='location'),
        ),
    ]
