# Generated by Django 5.2.14 on 2026-07-08 07:33

import django.core.validators
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_serviceticket_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload jpg, png, webp or pdf. Max 2 MB.', null=True, upload_to='tickets/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'pdf']), tickets.models.validate_file_size], verbose_name='attachment'),
        ),
    ]
