# Generated by Django 5.2.14 on 2026-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_location'),
        ('tickets', '0005_serviceticket_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='asset',
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='service_tickets', to='assets.asset', verbose_name='assets'),
        ),
    ]
